[project]
name = "pinholecamera"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "opencv-python",
    "matplotlib>=3.10.6",
    "opencv-python>=4.12.0.88",
    "ultralytics>=8.3.195",
]
